/* Daily Verse lists (King James Version, public domain). Every verse is a complete thought. */
const DV_LITTLE=[
["In the beginning God created the heaven and the earth.","Genesis 1:1"],
["And God saw every thing that he had made, and, behold, it was very good.","Genesis 1:31"],
["So God created man in his own image, in the image of God created he him; male and female created he them.","Genesis 1:27"],
["The LORD shall fight for you, and ye shall hold your peace.","Exodus 14:14"],
["The LORD is my shepherd; I shall not want.","Psalm 23:1"],
["What time I am afraid, I will trust in thee.","Psalm 56:3"],
["This is the day which the LORD hath made; we will rejoice and be glad in it.","Psalm 118:24"],
["Make a joyful noise unto the LORD, all ye lands.","Psalm 100:1"],
["Thy word is a lamp unto my feet, and a light unto my path.","Psalm 119:105"],
["O give thanks unto the LORD; for he is good: for his mercy endureth for ever.","Psalm 136:1"],
["God is our refuge and strength, a very present help in trouble.","Psalm 46:1"],
["I will praise thee; for I am fearfully and wonderfully made.","Psalm 139:14"],
["My help cometh from the LORD, which made heaven and earth.","Psalm 121:2"],
["Let every thing that hath breath praise the LORD. Praise ye the LORD.","Psalm 150:6"],
["I was glad when they said unto me, Let us go into the house of the LORD.","Psalm 122:1"],
["The LORD is my light and my salvation; whom shall I fear?","Psalm 27:1"],
["I will both lay me down in peace, and sleep: for thou, LORD, only makest me dwell in safety.","Psalm 4:8"],
["The heavens declare the glory of God; and the firmament sheweth his handywork.","Psalm 19:1"],
["I will bless the LORD at all times: his praise shall continually be in my mouth.","Psalm 34:1"],
["Bless the LORD, O my soul: and all that is within me, bless his holy name.","Psalm 103:1"],
["For he shall give his angels charge over thee, to keep thee in all thy ways.","Psalm 91:11"],
["The LORD is on my side; I will not fear: what can man do unto me?","Psalm 118:6"],
["Behold, how good and how pleasant it is for brethren to dwell together in unity!","Psalm 133:1"],
["Shew me thy ways, O LORD; teach me thy paths.","Psalm 25:4"],
["Create in me a clean heart, O God; and renew a right spirit within me.","Psalm 51:10"],
["A friend loveth at all times.","Proverbs 17:17"],
["A soft answer turneth away wrath: but grievous words stir up anger.","Proverbs 15:1"],
["Trust in the LORD with all thine heart; and lean not unto thine own understanding.","Proverbs 3:5"],
["Pleasant words are as an honeycomb, sweet to the soul, and health to the bones.","Proverbs 16:24"],
["Fear not: for I have redeemed thee, I have called thee by thy name; thou art mine.","Isaiah 43:1"],
["Blessed are the peacemakers: for they shall be called the children of God.","Matthew 5:9"],
["Blessed are the pure in heart: for they shall see God.","Matthew 5:8"],
["Blessed are the merciful: for they shall obtain mercy.","Matthew 5:7"],
["Follow me, and I will make you fishers of men.","Matthew 4:19"],
["Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be opened unto you.","Matthew 7:7"],
["For where two or three are gathered together in my name, there am I in the midst of them.","Matthew 18:20"],
["Come unto me, all ye that labour and are heavy laden, and I will give you rest.","Matthew 11:28"],
["With men this is impossible; but with God all things are possible.","Matthew 19:26"],
["Ye are the light of the world. A city that is set on an hill cannot be hid.","Matthew 5:14"],
["Thou shalt love thy neighbour as thyself.","Mark 12:31"],
["And Jesus increased in wisdom and stature, and in favour with God and man.","Luke 2:52"],
["For with God nothing shall be impossible.","Luke 1:37"],
["And as ye would that men should do to you, do ye also to them likewise.","Luke 6:31"],
["Be ye therefore merciful, as your Father also is merciful.","Luke 6:36"],
["For unto you is born this day in the city of David a Saviour, which is Christ the Lord.","Luke 2:11"],
["For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.","John 3:16"],
["I am the light of the world: he that followeth me shall not walk in darkness, but shall have the light of life.","John 8:12"],
["I am the good shepherd: the good shepherd giveth his life for the sheep.","John 10:11"],
["This is my commandment, That ye love one another, as I have loved you.","John 15:12"],
["A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.","John 13:34"],
["Be not overcome of evil, but overcome evil with good.","Romans 12:21"],
["If God be for us, who can be against us?","Romans 8:31"],
["And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.","Ephesians 4:32"],
["Children, obey your parents in the Lord: for this is right.","Ephesians 6:1"],
["I can do all things through Christ which strengtheneth me.","Philippians 4:13"],
["Rejoice in the Lord alway: and again I say, Rejoice.","Philippians 4:4"],
["Children, obey your parents in all things: for this is well pleasing unto the Lord.","Colossians 3:20"],
["Rejoice evermore. Pray without ceasing. In every thing give thanks: for this is the will of God in Christ Jesus concerning you.","1 Thessalonians 5:16-18"],
["Jesus Christ the same yesterday, and to day, and for ever.","Hebrews 13:8"],
["Draw nigh to God, and he will draw nigh to you.","James 4:8"],
["We love him, because he first loved us.","1 John 4:19"],
["Beloved, if God so loved us, we ought also to love one another.","1 John 4:11"],
["He that loveth not knoweth not God; for God is love.","1 John 4:8"],
["It is more blessed to give than to receive.","Acts 20:35"],
["God loveth a cheerful giver.","2 Corinthians 9:7"],
["As for me and my house, we will serve the LORD.","Joshua 24:15"],
["But seek ye first the kingdom of God, and his righteousness; and all these things shall be added unto you.","Matthew 6:33"]
];
const DV_OLDER=[
["Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.","Joshua 1:9"],
["Be strong and of a good courage, fear not, nor be afraid of them: for the LORD thy God, he it is that doth go with thee; he will not fail thee, nor forsake thee.","Deuteronomy 31:6"],
["And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy might.","Deuteronomy 6:5"],
["O taste and see that the LORD is good: blessed is the man that trusteth in him.","Psalm 34:8"],
["Delight thyself also in the LORD; and he shall give thee the desires of thine heart.","Psalm 37:4"],
["I will instruct thee and teach thee in the way which thou shalt go: I will guide thee with mine eye.","Psalm 32:8"],
["Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are pleasures for evermore.","Psalm 16:11"],
["Thy word have I hid in mine heart, that I might not sin against thee.","Psalm 119:11"],
["My flesh and my heart faileth: but God is the strength of my heart, and my portion for ever.","Psalm 73:26"],
["For a day in thy courts is better than a thousand. I had rather be a doorkeeper in the house of my God, than to dwell in the tents of wickedness.","Psalm 84:10"],
["Wherewithal shall a young man cleanse his way? by taking heed thereto according to thy word.","Psalm 119:9"],
["He healeth the broken in heart, and bindeth up their wounds.","Psalm 147:3"],
["The LORD is nigh unto all them that call upon him, to all that call upon him in truth.","Psalm 145:18"],
["Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.","Psalm 46:10"],
["In all thy ways acknowledge him, and he shall direct thy paths.","Proverbs 3:6"],
["Train up a child in the way he should go: and when he is old, he will not depart from it.","Proverbs 22:6"],
["Hatred stirreth up strifes: but love covereth all sins.","Proverbs 10:12"],
["Keep thy heart with all diligence; for out of it are the issues of life.","Proverbs 4:23"],
["Iron sharpeneth iron; so a man sharpeneth the countenance of his friend.","Proverbs 27:17"],
["Commit thy works unto the LORD, and thy thoughts shall be established.","Proverbs 16:3"],
["The name of the LORD is a strong tower: the righteous runneth into it, and is safe.","Proverbs 18:10"],
["A merry heart doeth good like a medicine: but a broken spirit drieth the bones.","Proverbs 17:22"],
["Two are better than one; because they have a good reward for their labour.","Ecclesiastes 4:9"],
["To every thing there is a season, and a time to every purpose under the heaven.","Ecclesiastes 3:1"],
["But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.","Isaiah 40:31"],
["Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee.","Isaiah 41:10"],
["Thou wilt keep him in perfect peace, whose mind is stayed on thee: because he trusteth in thee.","Isaiah 26:3"],
["For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an expected end.","Jeremiah 29:11"],
["Call unto me, and I will answer thee, and shew thee great and mighty things, which thou knowest not.","Jeremiah 33:3"],
["It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning: great is thy faithfulness.","Lamentations 3:22-23"],
["He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?","Micah 6:8"],
["The LORD is good, a strong hold in the day of trouble; and he knoweth them that trust in him.","Nahum 1:7"],
["Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.","Matthew 5:16"],
["For if ye forgive men their trespasses, your heavenly Father will also forgive you.","Matthew 6:14"],
["For where your treasure is, there will your heart be also.","Matthew 6:21"],
["Therefore all things whatsoever ye would that men should do to you, do ye even so to them.","Matthew 7:12"],
["Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind. This is the first and great commandment.","Matthew 22:37-38"],
["Inasmuch as ye have done it unto one of the least of these my brethren, ye have done it unto me.","Matthew 25:40"],
["And, lo, I am with you alway, even unto the end of the world.","Matthew 28:20"],
["If thou canst believe, all things are possible to him that believeth.","Mark 9:23"],
["For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many.","Mark 10:45"],
["Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father, but by me.","John 14:6"],
["Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.","John 14:27"],
["I am the vine, ye are the branches: He that abideth in me, and I in him, the same bringeth forth much fruit: for without me ye can do nothing.","John 15:5"],
["In the world ye shall have tribulation: but be of good cheer; I have overcome the world.","John 16:33"],
["And ye shall know the truth, and the truth shall make you free.","John 8:32"],
["And we know that all things work together for good to them that love God, to them who are the called according to his purpose.","Romans 8:28"],
["But God commendeth his love toward us, in that, while we were yet sinners, Christ died for us.","Romans 5:8"],
["Be kindly affectioned one to another with brotherly love; in honour preferring one another.","Romans 12:10"],
["But thanks be to God, which giveth us the victory through our Lord Jesus Christ.","1 Corinthians 15:57"],
["My grace is sufficient for thee: for my strength is made perfect in weakness.","2 Corinthians 12:9"],
["Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.","2 Corinthians 5:17"],
["And let us not be weary in well doing: for in due season we shall reap, if we faint not.","Galatians 6:9"],
["But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance.","Galatians 5:22-23"],
["And the peace of God, which passeth all understanding, shall keep your hearts and minds through Christ Jesus.","Philippians 4:7"],
["Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ.","Philippians 1:6"],
["And whatsoever ye do, do it heartily, as to the Lord, and not unto men.","Colossians 3:23"],
["Let no man despise thy youth; but be thou an example of the believers, in word, in conversation, in charity, in spirit, in faith, in purity.","1 Timothy 4:12"],
["For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.","2 Timothy 1:7"],
["Now faith is the substance of things hoped for, the evidence of things not seen.","Hebrews 11:1"],
["If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.","James 1:5"],
["But be ye doers of the word, and not hearers only, deceiving your own selves.","James 1:22"],
["If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.","1 John 1:9"],
["My little children, let us not love in word, neither in tongue; but in deed and in truth.","1 John 3:18"],
["Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him.","Revelation 3:20"]
];
