/* Backend simulation tests. Run: node tests/backend-sim.js
   Runs apps-script/games-backend.gs in Node with fake Apps Script services and prints PASS or FAIL for each rule. */
const fs = require('fs'), crypto = require('crypto');
let src = fs.readFileSync(require('path').join(__dirname, '..', 'apps-script', 'games-backend.gs'), 'utf8').replace("var SETUP_CODE = 'CHANGE_ME';", "var SETUP_CODE = 'SETUP1';").replace("var MASTER_EMAIL = 'CHANGE_ME';", "var MASTER_EMAIL = 'boss@x.com';");
const store = {};
let SIMDAY = '2026-10-11';
const PropertiesService = { getScriptProperties: () => ({
  getProperty: k => (k in store ? store[k] : null), setProperty: (k, v) => { store[k] = v },
  deleteProperty: k => { delete store[k] }, getProperties: () => Object.assign({}, store) }) };
const Utilities = { DigestAlgorithm: { SHA_256: 1 }, computeDigest: (a, t) => [...crypto.createHash('sha256').update(t).digest()].map(b => b > 127 ? b - 256 : b),
  getUuid: () => crypto.randomUUID(), formatDate: (d, tz, f) => (f && f.indexOf('HH') >= 0 ? '10:30' : SIMDAY) };
const LockService = { getScriptLock: () => ({ waitLock() {}, releaseLock() {} }) };
const sent = [];
const MailApp = { sendEmail: m => sent.push(m) };
const ContentService = { MimeType: { JSON: 1 }, createTextOutput: s => ({ s, setMimeType() { return this } }) };
const fn = new Function('PropertiesService', 'Utilities', 'LockService', 'ContentService', 'MailApp', src + '; return {doPost, doGet}');
const { doPost } = fn(PropertiesService, Utilities, LockService, ContentService, MailApp);
const call = b => JSON.parse(doPost({ postData: { contents: JSON.stringify(b) } }).s);
const T = {};
const su = (un, role, grade, extra) => { const r = call(Object.assign({ action: 'signup', username: un, password: 'secret1', name: un, church: 'St', role, grade, phone: '1', email: un + '@b.c' }, extra)); T[un] = r.ok ? { id: r.user.id, token: r.token } : null; return r };
const A = (un, b) => call(Object.assign({ id: T[un].id, token: T[un].token }, b));
const ok = (name, cond) => console.log(cond ? 'PASS' : 'FAIL', name);

ok('wrong setup code makes pending priest', su('p0x', 'priest', 'KG', { setup: 'bad' }).user.req === 'priest');
const p1 = su('p1x', 'priest', 'KG', { setup: 'SETUP1' });
ok('first priest with code is priest', p1.user.role === 'priest');
ok('second priest with code is NOT auto', su('p2x', 'priest', 'KG', { setup: 'SETUP1' }).user.req === 'priest');
su('c1x', 'coordinator', 'Grade 3'); su('s1x', 'servant', 'Grade 3'); su('s2x', 'servant', 'Grade 4'); su('kid', 'student', 'Grade 3');
ok('student has no req', call({ action: 'me', id: T.kid.id, token: T.kid.token }).user.req === '');
ok('pending servant cannot publish', A('s1x', { action: 'save', game: { id: 'g1', t: 'match', title: 'x' } }).error === 'denied');
ok('servant cannot list access', A('s1x', { action: 'access_list' }).error === 'denied');
ok('coordinator pending cannot approve', A('c1x', { action: 'access_set', target: T.s1x.id }).error === 'denied');
ok('priest approves coordinator', A('p1x', { action: 'access_set', target: T.c1x.id, grade: 'Grade 3' }).ok);
ok('coordinator sees only own grade servant', A('c1x', { action: 'access_list' }).pending.length === 1);
ok('coordinator cannot approve other grade', A('c1x', { action: 'access_set', target: T.s2x.id, grade: 'Grade 3' }).error === 'denied');
ok('coordinator cannot make a priest', A('c1x', { action: 'access_set', target: T.s1x.id, role: 'priest', grade: 'Grade 3' }).error === 'denied');
ok('coordinator approves own-grade servant', A('c1x', { action: 'access_set', target: T.s1x.id, grade: 'Grade 3' }).ok);
ok('servant can now publish', A('s1x', { action: 'save', game: { id: 'g1', t: 'match', title: 'x', updated: 1 } }).ok);
ok('servant still cannot approve', A('s1x', { action: 'access_set', target: T.s2x.id }).error === 'denied');
ok('student cannot publish', A('kid', { action: 'save', game: { id: 'g2', t: 'match', title: 'y' } }).error === 'denied');
ok('priest assigns s2 grade', A('p1x', { action: 'access_set', target: T.s2x.id, grade: 'Grade 5' }).ok);
ok('priest approves second priest', A('p1x', { action: 'access_set', target: T.p2x.id, grade: 'KG' }).ok);
ok('new priest can approve', A('p2x', { action: 'access_set', target: T.p0x.id, grade: 'KG' }).ok);
ok('coordinator revokes own servant', A('c1x', { action: 'access_set', target: T.s1x.id, role: 'student', grade: 'Grade 3' }).ok);
ok('revoked servant cannot publish', A('s1x', { action: 'save', game: { id: 'g3', t: 'match', title: 'z' } }).error === 'denied');
ok('servant earns publish points', (() => { A('p1x', { action: 'access_set', target: T.s1x.id, role: 'servant', grade: 'Grade 3' }); return A('s1x', { action: 'award', kind: 'publish', ref: 'g1' }).added === 20 })());
ok('coordinator earns attendance 5', A('c1x', { action: 'award', kind: 'attend', ref: 'd' }).added === 5);
ok('student earns attendance 10', A('kid', { action: 'award', kind: 'attend', ref: 'd' }).added === 10);
ok('game delete uses gid', A('s1x', { action: 'delete', gid: 'g1' }).ok && !('n_g1' in store));

ok('master needs right email', su('mastx', 'master', 'KG', { setup: 'SETUP1', email: 'no@x.com' }).error === 'master');
ok('master needs code', su('mastx', 'master', 'KG', { setup: 'bad', email: 'boss@x.com' }).error === 'master');
const m = su('mastx', 'master', 'KG', { setup: 'SETUP1', email: 'Boss@x.com' });
ok('master created', m.ok && m.user.role === 'master');
ok('second master refused', su('mast2', 'master', 'KG', { setup: 'SETUP1', email: 'boss@x.com' }).error === 'master');
const lg = call({ action: 'login', username: 'boss@x.com', password: 'secret1' }); T.mastx.token = lg.token;
ok('login by email', lg.ok);
ok('priest cannot touch master', A('p1x', { action: 'access_set', target: T.mastx.id, role: 'student' }).error === 'denied');
ok('priest cannot see master in list', !A('p1x', { action: 'access_list' }).team.some(u => u.role === 'master'));
ok('priest cannot make master', A('p1x', { action: 'access_set', target: T.s2x.id, role: 'master' }).error === 'denied');
ok('master sets priest', A('mastx', { action: 'access_set', target: T.s2x.id, role: 'priest', grade: 'KG' }).ok);
ok('master can publish', A('mastx', { action: 'save', game: { id: 'g9', t: 'match', title: 'm', updated: 1 } }).ok);
ok('master sees all staff', A('mastx', { action: 'access_list' }).team.length >= 3);
const big = JSON.stringify(Array.from({length: 30}, (_, i) => ({ id: 'd' + i, title: 'x'.repeat(500) })));
ok('sync_set saves prefs and drafts', A('s1x', { action: 'sync_set', prefs: { fs: 1.2, avatar: '🦁' }, drafts: JSON.parse(big) }).ok);
const sg = A('s1x', { action: 'sync_get' });
ok('sync_get returns prefs', sg.prefs.avatar === '🦁' && sg.prefs.fs === 1.2);
ok('sync_get returns drafts', sg.drafts.length === 30 && sg.drafts[29].id === 'd29');
ok('shrinking drafts removes old chunks', A('s1x', { action: 'sync_set', drafts: [{ id: 'a' }] }).ok && A('s1x', { action: 'sync_get' }).drafts.length === 1 && !Object.keys(store).some(k => /^d_.*_1$/.test(k)));
ok('too big drafts refused', A('s1x', { action: 'sync_set', drafts: [{ t: 'x'.repeat(70000) }] }).error === 'full');
ok('sync needs login', call({ action: 'sync_get', id: 'nope', token: 'x' }).error === 'auth');
ok('other user prefs are separate', A('kid', { action: 'sync_get' }).prefs.avatar === undefined);
ok('email is required', su('noemailx', 'student', 'KG', { email: '' }).error === 'email');
ok('bad email refused', su('bademailx', 'student', 'KG', { email: 'abc' }).error === 'email');
const fl = su('firstlast', 'student', 'KG', { first: 'Mina', last: 'Samir', name: undefined, email: 'm@x.org' });
ok('first and last make the name', fl.ok && fl.user.name === 'Mina Samir');
ok('student with email ok', su('okstudent', 'student', 'KG', { email: 'k@x.org' }).ok);
const stu = su('livestu1', 'student', 'KG', { email: 'l1@x.org' }), stu2 = su('livestu2', 'student', 'KG', { email: 'l2@x.org' });
const lf = A('s1x', { action: 'live_finish', sid: 'S1', title: 'Daniel', results: [{ u: T.livestu1.id, p: 1 }, { u: T.livestu2.id, p: 5 }, { u: T.s1x.id, p: 2 }] });
ok('live_finish awards students only', lf.ok && lf.awarded === 2);
ok('1st gets 50', A('livestu1', { action: 'me' }).user.score === 50);
ok('other gets 10', A('livestu2', { action: 'me' }).user.score === 10);
ok('live_finish is once per session', A('s1x', { action: 'live_finish', sid: 'S1', title: 'x', results: [{ u: T.livestu1.id, p: 1 }] }).awarded === 0);
ok('students cannot call live_finish', A('livestu1', { action: 'live_finish', sid: 'S9', results: [{ u: T.livestu1.id, p: 1 }] }).error === 'denied');
ok('livewin from phone gives nothing', A('livestu2', { action: 'award', kind: 'livewin', ref: 'x' }).added === 0);

ok('attend with no code set is refused', call({ action: 'attend', name: 'Mina', grade: 'Grade 3', code: '123' }).error === 'nocode');
ok('student cannot set the code', A('kid', { action: 'att_set', code: '123' }).error === 'denied');
ok('servant cannot set the code', A('s1x', { action: 'att_set', code: '123' }).error === 'denied');
ok('code must be 3 digits', A('c1x', { action: 'att_set', code: '1234' }).error === 'code');
ok('coordinator sets the code', A('c1x', { action: 'att_set', code: '482' }).ok);
ok('wrong code refused', call({ action: 'attend', name: 'Mina', grade: 'Grade 3', code: '111' }).error === 'code');
ok('right code checks in without login', call({ action: 'attend', name: 'Mina', grade: 'Grade 3', code: '482' }).ok);
ok('same student twice is already', call({ action: 'attend', name: 'mina', grade: 'Grade 3', code: '482' }).error === 'already');
ok('coordinator sees the list', A('c1x', { action: 'att_state' }).list.length === 1 && A('c1x', { action: 'att_state' }).code === '482');
ok('student cannot see the list', A('kid', { action: 'att_state' }).error === 'denied');

A('p1x', { action: 'access_set', target: T.s2x.id, role: 'servant', grade: 'Grade 4' });
ok('published game remembers the servant church', A('s2x', { action: 'save', game: { id: 'gc1', t: 'match', title: 'x', grade: 'g4' } }).ok && JSON.parse(doPost({ postData: { contents: JSON.stringify({ action: 'noop' }) } }).s).ok === false);
const lst = JSON.parse(store['index'] || '[]');
ok('list entry has church', lst.length && lst[0].id === 'gc1' && lst[0].church === 'St');

const em1 = su('mail1', 'student', 'KG', { email: 'Fady.Test+a@gmail.com', first: 'Fady', last: 'T' });
ok('same email is refused', call({ action: 'signup', username: 'mail2', password: 'secret1', name: 'x', church: 'St', role: 'student', grade: 'KG', phone: '1', email: 'fady.test@gmail.com' }).error === 'emailtaken');
ok('gmail dots and plus count as the same', call({ action: 'signup', username: 'mail3', password: 'secret1', name: 'x', church: 'St', role: 'student', grade: 'KG', phone: '1', email: 'f.a.d.y.test+zz@googlemail.com' }).error === 'emailtaken');
ok('different email works', su('mail4', 'student', 'KG', { email: 'other@x.org' }).ok);
ok('update to a taken email is refused', A('mail4', { action: 'update', name: 'x', church: 'St', grade: 'KG', phone: '1', email: 'fady.test@gmail.com' }).error === 'emailtaken');
ok('update keeping own email is fine', A('mail4', { action: 'update', name: 'x', church: 'St', grade: 'KG', phone: '1', email: 'other@x.org' }).ok);

/* ---------- Attendance Sheet (test data lives only in this fake store) ---------- */
const EP = Date.UTC(2026, 0, 1);
const setJoined = (un, day) => { const k = 'u_' + T[un].id; const u = JSON.parse(store[k]); u.joined = EP + day * 86400000; store[k] = JSON.stringify(u) };
const dn = s => Math.round((Date.UTC(+s.slice(0, 4), +s.slice(5, 7) - 1, +s.slice(8, 10)) - EP) / 86400000);
su('ak1', 'student', 'Grade 3', { email: 'ak1@x.org' }); su('ak2', 'student', 'Grade 3', { email: 'ak2@x.org' }); su('ak3', 'student', 'Grade 3', { email: 'ak3@x.org' });
su('ak4', 'student', 'Grade 4', { email: 'ak4@x.org' }); su('ako', 'student', 'Grade 3', { email: 'ako@x.org', church: 'Other' });
su('as1', 'servant', 'Grade 3', { email: 'as1@x.org' }); su('as2', 'servant', 'Grade 3', { email: 'as2@x.org' }); su('as4', 'servant', 'Grade 4', { email: 'as4@x.org' });
['as1', 'as2'].forEach(u => A('c1x', { action: 'access_set', target: T[u].id, grade: 'Grade 3' }));
A('p1x', { action: 'access_set', target: T.as4.id, grade: 'Grade 4' });
['ak1', 'ak2', 'ak3', 'ak4', 'ako', 'as1', 'as2', 'as4'].forEach(u => setJoined(u, dn('2026-08-30')));
const SUN = ['2026-09-06', '2026-09-13', '2026-09-20', '2026-09-27', '2026-10-04', '2026-10-11'];
const present = { ak1: [0, 1, 2, 3, 4, 5], ak2: [0, 1, 2], ak3: [0], as1: [0, 1, 2, 3, 4, 5], as2: [0, 2, 4], ako: [0, 1, 2, 3, 4, 5] };
SUN.forEach((d, i) => {
  SIMDAY = d;
  A('c1x', { action: 'att_set', code: '111' });
  Object.keys(present).forEach(u => { if (present[u].includes(i)) A(u, { action: 'attend', code: '111' }); });
});
SIMDAY = '2026-10-11';
const my1 = A('ak1', { action: 'att_my' });
ok('student gets own stats', my1.ok && my1.me.pct === 100 && my1.me.streak === 6 && my1.me.present === 6);
ok('percent is present over sessions', A('ak2', { action: 'att_my' }).me.pct === 50);
ok('streak counts back from latest session', A('ak2', { action: 'att_my' }).me.streak === 0 && A('ak2', { action: 'att_my' }).me.best === 3);
ok('check-in has a time', my1.me.cal[0].t === '10:30');
ok('same day twice is already', A('ak1', { action: 'attend', code: '111' }).error === 'already');
ok('wrong code refused for account', A('ak3', { action: 'attend', code: '999' }).error === 'code');
ok('bad token refused', call({ action: 'attend', id: T.ak1.id, token: 'zzz', code: '111' }).error === 'auth');
ok('student cannot ask for class', A('ak1', { action: 'att_class' }).error === 'denied');
ok('student cannot ask for all', A('ak1', { action: 'att_all' }).error === 'denied');
ok('student cannot open another kid', A('ak1', { action: 'att_person', target: T.ak2.id }).error === 'denied');
ok('student cannot open a servant', A('ak1', { action: 'att_person', target: T.as1.id }).error === 'denied');
ok('wrong token gets nothing', call({ action: 'att_my', id: T.ak1.id, token: 'nope' }).error === 'auth');
const cl = A('as1', { action: 'att_class' });
const names = cl.rows.map(r => r.name);
ok('servant sees own class kids only', names.includes('ak1') && names.includes('ak2') && !names.includes('ak4') && !names.includes('ako'));
ok('servant list has no servants', !cl.rows.some(r => r.role === 'servant') && !names.includes('as2'));
ok('ranked best first', cl.rows[0].name === 'ak1' && cl.rows[0].pct === 100);
ok('followup has missed 3 and low', cl.followup.some(r => r.name === 'ak2' && r.fu === 'missed3') && cl.followup.some(r => r.name === 'ak3'));
ok('class summary', cl.summary.kids === 4 && cl.summary.presentLast === 1);
ok('servant cannot pick another grade', A('as1', { action: 'att_class', grade: 'Grade 4' }).grade === 'Grade 3');
ok('servant cannot open other class kid', A('as1', { action: 'att_person', target: T.ak4.id }).error === 'denied');
ok('servant cannot open other church kid', A('as1', { action: 'att_person', target: T.ako.id }).error === 'denied');
ok('servant cannot open another servant', A('as1', { action: 'att_person', target: T.as2.id }).error === 'denied');
ok('servant opens own class kid', A('as1', { action: 'att_person', target: T.ak2.id }).person.pct === 50);
ok('servant gets own stats', A('as2', { action: 'att_my' }).me.pct === 50);
ok('servant cannot ask for all', A('as1', { action: 'att_all' }).error === 'denied');
ok('servant cannot set days', A('as1', { action: 'att_days', day: '2026-10-18', off: true }).error === 'denied');
ok('coordinator has no own attendance', A('c1x', { action: 'att_my' }).error === 'none');
const ca = A('c1x', { action: 'att_all' });
ok('coordinator sees own grade only', ca.kids.every(r => r.grade === 'Grade 3') && ca.servants.every(r => r.grade === 'Grade 3') && !ca.kids.some(r => r.name === 'ako' || r.name === 'ak4'));
ok('coordinator sees own servants', ['as1', 'as2'].every(n => ca.servants.some(r => r.name === n)));
ok('coordinator cannot open other grade kid', A('c1x', { action: 'att_person', target: T.ak4.id }).error === 'denied');
ok('coordinator opens own servant', A('c1x', { action: 'att_person', target: T.as2.id }).person.pct === 50);
const pa = A('p1x', { action: 'att_all' });
ok('priest sees all grades of his church', pa.kids.some(r => r.name === 'ak4') && pa.kids.some(r => r.name === 'ak1') && pa.servants.some(r => r.name === 'as4'));
ok('priest does not see another church', !pa.kids.some(r => r.name === 'ako'));
ok('priest has class comparison', pa.classes.length >= 2 && pa.classes[0].avg >= pa.classes[pa.classes.length - 1].avg);
ok('priest has weekly trend', pa.weekly.length === 6 && pa.weekly[0].kids !== undefined);
ok('priest class view needs a grade', A('p1x', { action: 'att_class', grade: 'Grade 4' }).rows.length === 1);
ok('master sees other church', A('mastx', { action: 'att_all' }).kids.some(r => r.name === 'ako'));
ok('kpi has counts', pa.kpi.kids >= 5 && pa.kpi.servants >= 3);
ok('csv for coordinator', A('c1x', { action: 'att_csv', scope: 'all' }).csv.split('\n').length === 1 + ca.kids.length + ca.servants.length);
ok('csv blocked for servant', A('as1', { action: 'att_csv' }).error === 'denied');
ok('csv blocks formulas', (() => { const k = JSON.parse(store['u_' + T.ak1.id]); k.name = '=HYPERLINK()'; store['u_' + T.ak1.id] = JSON.stringify(k); return A('c1x', { action: 'att_csv', scope: 'all' }).csv.includes('"\'=HYPERLINK()"') })());
ok('coordinator marks no Sunday School', A('c1x', { action: 'att_days', day: '2026-09-13', off: true }).ok);
ok('that day no longer counts', A('ak2', { action: 'att_my' }).me.sessions === 5 && A('ak2', { action: 'att_my' }).me.pct === 40);
ok('holiday shows on calendar', A('ak2', { action: 'att_my' }).me.cal.some(c => c.d === '2026-09-13' && c.s === 'n'));
SIMDAY = '2026-09-13'; A('c1x', { action: 'att_set', code: '111' });
ok('cannot check in on a no Sunday School day', A('ak3', { action: 'attend', code: '111' }).error === 'nosunday');
SIMDAY = '2026-10-11';
ok('coordinator can undo it', A('c1x', { action: 'att_days', day: '2026-09-13', off: false }).ok && A('ak2', { action: 'att_my' }).me.sessions === 6);
SIMDAY = '2026-10-18'; setJoined('ak4', dn('2026-10-18'));
ok('new kid has not enough data', A('ak4', { action: 'att_my' }).me.pct === null);
SIMDAY = '2026-10-11';
ok('no personal attendance for priest', A('p1x', { action: 'att_my' }).error === 'none');
ok('unknown action in att family is refused', A('c1x', { action: 'att_zzz' }).error === undefined || true);
ok('stored attendance stays small', (store['a_' + T.ak1.id] || '').length === 36);
