/* Backend simulation tests. Run: node tests/backend-sim.js
   Runs apps-script/games-backend.gs in Node with fake Apps Script services and prints PASS or FAIL for each rule. */
const fs = require('fs'), crypto = require('crypto');
let src = fs.readFileSync(require('path').join(__dirname, '..', 'apps-script', 'games-backend.gs'), 'utf8').replace("var SETUP_CODE = 'CHANGE_ME';", "var SETUP_CODE = 'SETUP1';").replace("var MASTER_EMAIL = 'CHANGE_ME';", "var MASTER_EMAIL = 'boss@x.com';");
const store = {};
let SIMDAY = '2026-10-11';
const PropertiesService = { getScriptProperties: () => ({
  getProperty: k => (k in store ? store[k] : null), setProperty: (k, v) => { store[k] = v },
  deleteProperty: k => { delete store[k] }, getProperties: () => Object.assign({}, store) }) };
const Utilities = { DigestAlgorithm: { SHA_256: 1 }, computeDigest: (a, t) => [...crypto.createHash('sha256').update(t).digest()].map(b => b > 127 ? b - 256 : b),
  getUuid: () => crypto.randomUUID(), formatDate: (d, tz, f) => (f && f.indexOf('HH') >= 0 ? '10:30' : SIMDAY) };
const LockService = { getScriptLock: () => ({ waitLock() {}, releaseLock() {} }) };
const sent = [];
const MailApp = { sendEmail: m => sent.push(m) };
const ContentService = { MimeType: { JSON: 1 }, createTextOutput: s => ({ s, setMimeType() { return this } }) };
const fn = new Function('PropertiesService', 'Utilities', 'LockService', 'ContentService', 'MailApp', src + '; return {doPost, doGet}');
const { doPost } = fn(PropertiesService, Utilities, LockService, ContentService, MailApp);
const call = b => JSON.parse(doPost({ postData: { contents: JSON.stringify(b) } }).s);
const T = {};
const su = (un, role, grade, extra) => { const r = call(Object.assign({ action: 'signup', username: un, password: 'secret1', name: un, church: 'St', role, grade, phone: '1', email: un + '@b.c' }, extra)); T[un] = r.ok ? { id: r.user.id, token: r.token } : null; return r };
const A = (un, b) => call(Object.assign({ id: T[un].id, token: T[un].token }, b));
const ok = (name, cond) => console.log(cond ? 'PASS' : 'FAIL', name);

ok('wrong setup code makes pending priest', su('p0x', 'priest', 'KG', { setup: 'bad' }).user.req === 'priest');
const p1 = su('p1x', 'priest', 'KG', { setup: 'SETUP1' });
ok('first priest with code is priest', p1.user.role === 'priest');
ok('second priest with code is NOT auto', su('p2x', 'priest', 'KG', { setup: 'SETUP1' }).user.req === 'priest');
su('c1x', 'coordinator', 'Grade 3'); su('s1x', 'servant', 'Grade 3'); su('s2x', 'servant', 'Grade 4'); su('kid', 'student', 'Grade 3');
ok('student has no req', call({ action: 'me', id: T.kid.id, token: T.kid.token }).user.req === '');
ok('pending servant cannot publish', A('s1x', { action: 'save', game: { id: 'g1', t: 'match', title: 'x' } }).error === 'denied');
ok('servant cannot list access', A('s1x', { action: 'access_list' }).error === 'denied');
ok('coordinator pending cannot approve', A('c1x', { action: 'access_set', target: T.s1x.id }).error === 'denied');
ok('priest approves coordinator', A('p1x', { action: 'access_set', target: T.c1x.id, grade: 'Grade 3' }).ok);
ok('coordinator sees only own grade servant', A('c1x', { action: 'access_list' }).pending.length === 1);
ok('coordinator cannot approve other grade', A('c1x', { action: 'access_set', target: T.s2x.id, grade: 'Grade 3' }).error === 'denied');
ok('coordinator cannot make a priest', A('c1x', { action: 'access_set', target: T.s1x.id, role: 'priest', grade: 'Grade 3' }).error === 'denied');
ok('coordinator approves own-grade servant', A('c1x', { action: 'access_set', target: T.s1x.id, grade: 'Grade 3' }).ok);
ok('servant can now publish', A('s1x', { action: 'save', game: { id: 'g1', t: 'match', title: 'x', updated: 1 } }).ok);
ok('servant still cannot approve', A('s1x', { action: 'access_set', target: T.s2x.id }).error === 'denied');
ok('student cannot publish', A('kid', { action: 'save', game: { id: 'g2', t: 'match', title: 'y' } }).error === 'denied');
ok('priest assigns s2 grade', A('p1x', { action: 'access_set', target: T.s2x.id, grade: 'Grade 5' }).ok);
ok('priest approves second priest', A('p1x', { action: 'access_set', target: T.p2x.id, grade: 'KG' }).ok);
ok('new priest can approve', A('p2x', { action: 'access_set', target: T.p0x.id, grade: 'KG' }).ok);
ok('coordinator revokes own servant', A('c1x', { action: 'access_set', target: T.s1x.id, role: 'student', grade: 'Grade 3' }).ok);
ok('revoked servant cannot publish', A('s1x', { action: 'save', game: { id: 'g3', t: 'match', title: 'z' } }).error === 'denied');
ok('servant earns publish points', (() => { A('p1x', { action: 'access_set', target: T.s1x.id, role: 'servant', grade: 'Grade 3' }); return A('s1x', { action: 'award', kind: 'publish', ref: 'g1' }).added === 20 })());
ok('coordinator earns attendance 5', A('c1x', { action: 'award', kind: 'attend', ref: 'd' }).added === 5);
ok('student earns attendance 10', A('kid', { action: 'award', kind: 'attend', ref: 'd' }).added === 10);
ok('game delete uses gid', A('s1x', { action: 'delete', gid: 'g1' }).ok && !('n_g1' in store));

ok('master needs right email', su('mastx', 'master', 'KG', { setup: 'SETUP1', email: 'no@x.com' }).error === 'master');
ok('master needs code', su('mastx', 'master', 'KG', { setup: 'bad', email: 'boss@x.com' }).error === 'master');
const m = su('mastx', 'master', 'KG', { setup: 'SETUP1', email: 'Boss@x.com' });
ok('master created', m.ok && m.user.role === 'master');
ok('second master refused', su('mast2', 'master', 'KG', { setup: 'SETUP1', email: 'boss@x.com' }).error === 'master');
const lg = call({ action: 'login', username: 'boss@x.com', password: 'secret1' }); T.mastx.token = lg.token;
ok('login by email', lg.ok);
ok('priest cannot touch master', A('p1x', { action: 'access_set', target: T.mastx.id, role: 'student' }).error === 'denied');
ok('priest cannot see master in list', !A('p1x', { action: 'access_list' }).team.some(u => u.role === 'master'));
ok('priest cannot make master', A('p1x', { action: 'access_set', target: T.s2x.id, role: 'master' }).error === 'denied');
ok('master sets priest', A('mastx', { action: 'access_set', target: T.s2x.id, role: 'priest', grade: 'KG' }).ok);
ok('master can publish', A('mastx', { action: 'save', game: { id: 'g9', t: 'match', title: 'm', updated: 1 } }).ok);
ok('master sees all staff', A('mastx', { action: 'access_list' }).team.length >= 3);
const big = JSON.stringify(Array.from({length: 30}, (_, i) => ({ id: 'd' + i, title: 'x'.repeat(500) })));
ok('sync_set saves prefs and drafts', A('s1x', { action: 'sync_set', prefs: { fs: 1.2, avatar: '🦁' }, drafts: JSON.parse(big) }).ok);
const sg = A('s1x', { action: 'sync_get' });
ok('sync_get returns prefs', sg.prefs.avatar === '🦁' && sg.prefs.fs === 1.2);
ok('sync_get returns drafts', sg.drafts.length === 30 && sg.drafts[29].id === 'd29');
ok('shrinking drafts removes old chunks', A('s1x', { action: 'sync_set', drafts: [{ id: 'a' }] }).ok && A('s1x', { action: 'sync_get' }).drafts.length === 1 && !Object.keys(store).some(k => /^d_.*_1$/.test(k)));
ok('too big drafts refused', A('s1x', { action: 'sync_set', drafts: [{ t: 'x'.repeat(70000) }] }).error === 'full');
ok('sync needs login', call({ action: 'sync_get', id: 'nope', token: 'x' }).error === 'auth');
ok('other user prefs are separate', A('kid', { action: 'sync_get' }).prefs.avatar === undefined);
ok('email is required', su('noemailx', 'student', 'KG', { email: '' }).error === 'email');
ok('bad email refused', su('bademailx', 'student', 'KG', { email: 'abc' }).error === 'email');
const fl = su('firstlast', 'student', 'KG', { first: 'Mina', last: 'Samir', name: undefined, email: 'm@x.org' });
ok('first and last make the name', fl.ok && fl.user.name === 'Mina Samir');
ok('student with email ok', su('okstudent', 'student', 'KG', { email: 'k@x.org' }).ok);
const stu = su('livestu1', 'student', 'KG', { email: 'l1@x.org' }), stu2 = su('livestu2', 'student', 'KG', { email: 'l2@x.org' });
const lf = A('s1x', { action: 'live_finish', sid: 'S1', title: 'Daniel', results: [{ u: T.livestu1.id, p: 1 }, { u: T.livestu2.id, p: 5 }, { u: T.s1x.id, p: 2 }] });
ok('live_finish awards students only', lf.ok && lf.awarded === 2);
ok('1st gets 50', A('livestu1', { action: 'me' }).user.score === 50);
ok('other gets 10', A('livestu2', { action: 'me' }).user.score === 10);
ok('live_finish is once per session', A('s1x', { action: 'live_finish', sid: 'S1', title: 'x', results: [{ u: T.livestu1.id, p: 1 }] }).awarded === 0);
ok('students cannot call live_finish', A('livestu1', { action: 'live_finish', sid: 'S9', results: [{ u: T.livestu1.id, p: 1 }] }).error === 'denied');
ok('livewin from phone gives nothing', A('livestu2', { action: 'award', kind: 'livewin', ref: 'x' }).added === 0);

ok('attend with no code set is refused', call({ action: 'attend', name: 'Mina', grade: 'Grade 3', code: '123' }).error === 'nocode');
ok('student cannot set the code', A('kid', { action: 'att_set', code: '123' }).error === 'denied');
ok('servant cannot set the code', A('s1x', { action: 'att_set', code: '123' }).error === 'denied');
ok('code must be 3 digits', A('c1x', { action: 'att_set', code: '1234' }).error === 'code');
ok('coordinator sets the code', A('c1x', { action: 'att_set', code: '482' }).ok);
ok('wrong code refused', call({ action: 'attend', name: 'Mina', grade: 'Grade 3', code: '111' }).error === 'code');
ok('right code checks in without login', call({ action: 'attend', name: 'Mina', grade: 'Grade 3', code: '482' }).ok);
ok('same student twice is already', call({ action: 'attend', name: 'mina', grade: 'Grade 3', code: '482' }).error === 'already');
ok('coordinator sees the list', A('c1x', { action: 'att_state' }).list.length === 1 && A('c1x', { action: 'att_state' }).code === '482');
ok('student cannot see the list', A('kid', { action: 'att_state' }).error === 'denied');

A('p1x', { action: 'access_set', target: T.s2x.id, role: 'servant', grade: 'Grade 4' });
ok('published game remembers the servant church', A('s2x', { action: 'save', game: { id: 'gc1', t: 'match', title: 'x', grade: 'g4' } }).ok && JSON.parse(doPost({ postData: { contents: JSON.stringify({ action: 'noop' }) } }).s).ok === false);
const lst = JSON.parse(store['index'] || '[]');
ok('list entry has church', lst.length && lst[0].id === 'gc1' && lst[0].church === 'St');

const em1 = su('mail1', 'student', 'KG', { email: 'Fady.Test+a@gmail.com', first: 'Fady', last: 'T' });
ok('same email is refused', call({ action: 'signup', username: 'mail2', password: 'secret1', name: 'x', church: 'St', role: 'student', grade: 'KG', phone: '1', email: 'fady.test@gmail.com' }).error === 'emailtaken');
ok('gmail dots and plus count as the same', call({ action: 'signup', username: 'mail3', password: 'secret1', name: 'x', church: 'St', role: 'student', grade: 'KG', phone: '1', email: 'f.a.d.y.test+zz@googlemail.com' }).error === 'emailtaken');
ok('different email works', su('mail4', 'student', 'KG', { email: 'other@x.org' }).ok);
ok('update to a taken email is refused', A('mail4', { action: 'update', name: 'x', church: 'St', grade: 'KG', phone: '1', email: 'fady.test@gmail.com' }).error === 'emailtaken');
ok('update keeping own email is fine', A('mail4', { action: 'update', name: 'x', church: 'St', grade: 'KG', phone: '1', email: 'other@x.org' }).ok);

/* ---------- Attendance Sheet (test data lives only in this fake store) ---------- */
const EP = Date.UTC(2026, 0, 1);
const setJoined = (un, day) => { const k = 'u_' + T[un].id; const u = JSON.parse(store[k]); u.joined = EP + day * 86400000; store[k] = JSON.stringify(u) };
const dn = s => Math.round((Date.UTC(+s.slice(0, 4), +s.slice(5, 7) - 1, +s.slice(8, 10)) - EP) / 86400000);
su('ak1', 'student', 'Grade 3', { email: 'ak1@x.org' }); su('ak2', 'student', 'Grade 3', { email: 'ak2@x.org' }); su('ak3', 'student', 'Grade 3', { email: 'ak3@x.org' });
su('ak4', 'student', 'Grade 4', { email: 'ak4@x.org' }); su('ako', 'student', 'Grade 3', { email: 'ako@x.org', church: 'Other' });
su('as1', 'servant', 'Grade 3', { email: 'as1@x.org' }); su('as2', 'servant', 'Grade 3', { email: 'as2@x.org' }); su('as4', 'servant', 'Grade 4', { email: 'as4@x.org' });
['as1', 'as2'].forEach(u => A('c1x', { action: 'access_set', target: T[u].id, grade: 'Grade 3' }));
A('p1x', { action: 'access_set', target: T.as4.id, grade: 'Grade 4' });
['ak1', 'ak2', 'ak3', 'ak4', 'ako', 'as1', 'as2', 'as4'].forEach(u => setJoined(u, dn('2026-08-30')));
const SUN = ['2026-09-06', '2026-09-13', '2026-09-20', '2026-09-27', '2026-10-04', '2026-10-11'];
const present = { ak1: [0, 1, 2, 3, 4, 5], ak2: [0, 1, 2], ak3: [0], as1: [0, 1, 2, 3, 4, 5], as2: [0, 2, 4], ako: [0, 1, 2, 3, 4, 5] };
SUN.forEach((d, i) => {
  SIMDAY = d;
  A('c1x', { action: 'att_set', code: '111' });
  Object.keys(present).forEach(u => { if (present[u].includes(i)) A(u, { action: 'attend', code: '111' }); });
});
SIMDAY = '2026-10-11';
const my1 = A('ak1', { action: 'att_my' });
ok('student gets own stats', my1.ok && my1.me.pct === 100 && my1.me.streak === 6 && my1.me.present === 6);
ok('percent is present over sessions', A('ak2', { action: 'att_my' }).me.pct === 50);
ok('streak counts back from latest session', A('ak2', { action: 'att_my' }).me.streak === 0 && A('ak2', { action: 'att_my' }).me.best === 3);
ok('check-in has a time', my1.me.cal[0].t === '10:30');
ok('same day twice is already', A('ak1', { action: 'attend', code: '111' }).error === 'already');
ok('wrong code refused for account', A('ak3', { action: 'attend', code: '999' }).error === 'code');
ok('bad token refused', call({ action: 'attend', id: T.ak1.id, token: 'zzz', code: '111' }).error === 'auth');
ok('student cannot ask for class', A('ak1', { action: 'att_class' }).error === 'denied');
ok('student cannot ask for all', A('ak1', { action: 'att_all' }).error === 'denied');
ok('student cannot open another kid', A('ak1', { action: 'att_person', target: T.ak2.id }).error === 'denied');
ok('student cannot open a servant', A('ak1', { action: 'att_person', target: T.as1.id }).error === 'denied');
ok('wrong token gets nothing', call({ action: 'att_my', id: T.ak1.id, token: 'nope' }).error === 'auth');
const cl = A('as1', { action: 'att_class' });
const names = cl.rows.map(r => r.name);
ok('servant sees own class kids only', names.includes('ak1') && names.includes('ak2') && !names.includes('ak4') && !names.includes('ako'));
ok('servant list has no servants', !cl.rows.some(r => r.role === 'servant') && !names.includes('as2'));
ok('ranked best first', cl.rows[0].name === 'ak1' && cl.rows[0].pct === 100);
ok('followup has missed 3 and low', cl.followup.some(r => r.name === 'ak2' && r.fu === 'missed3') && cl.followup.some(r => r.name === 'ak3'));
ok('class summary', cl.summary.kids === 4 && cl.summary.presentLast === 1);
ok('servant cannot pick another grade', A('as1', { action: 'att_class', grade: 'Grade 4' }).grade === 'Grade 3');
ok('servant cannot open other class kid', A('as1', { action: 'att_person', target: T.ak4.id }).error === 'denied');
ok('servant cannot open other church kid', A('as1', { action: 'att_person', target: T.ako.id }).error === 'denied');
ok('servant cannot open another servant', A('as1', { action: 'att_person', target: T.as2.id }).error === 'denied');
ok('servant opens own class kid', A('as1', { action: 'att_person', target: T.ak2.id }).person.pct === 50);
ok('servant gets own stats', A('as2', { action: 'att_my' }).me.pct === 50);
ok('servant cannot ask for all', A('as1', { action: 'att_all' }).error === 'denied');
ok('servant cannot set days', A('as1', { action: 'att_days', day: '2026-10-18', off: true }).error === 'denied');
ok('coordinator has no own attendance', A('c1x', { action: 'att_my' }).error === 'none');
const ca = A('c1x', { action: 'att_all' });
ok('coordinator sees own grade only', ca.kids.every(r => r.grade === 'Grade 3') && ca.servants.every(r => r.grade === 'Grade 3') && !ca.kids.some(r => r.name === 'ako' || r.name === 'ak4'));
ok('coordinator sees own servants', ['as1', 'as2'].every(n => ca.servants.some(r => r.name === n)));
ok('coordinator cannot open other grade kid', A('c1x', { action: 'att_person', target: T.ak4.id }).error === 'denied');
ok('coordinator opens own servant', A('c1x', { action: 'att_person', target: T.as2.id }).person.pct === 50);
const pa = A('p1x', { action: 'att_all' });
ok('priest sees all grades of his church', pa.kids.some(r => r.name === 'ak4') && pa.kids.some(r => r.name === 'ak1') && pa.servants.some(r => r.name === 'as4'));
ok('priest does not see another church', !pa.kids.some(r => r.name === 'ako'));
ok('priest has class comparison', pa.classes.length >= 2 && pa.classes[0].avg >= pa.classes[pa.classes.length - 1].avg);
ok('priest has weekly trend', pa.weekly.length === 6 && pa.weekly[0].kids !== undefined);
ok('priest class view needs a grade', A('p1x', { action: 'att_class', grade: 'Grade 4' }).rows.length === 1);
ok('master sees other church', A('mastx', { action: 'att_all' }).kids.some(r => r.name === 'ako'));
ok('kpi has counts', pa.kpi.kids >= 5 && pa.kpi.servants >= 3);
ok('csv for coordinator', A('c1x', { action: 'att_csv', scope: 'all' }).csv.split('\n').length === 1 + ca.kids.length + ca.servants.length);
ok('csv blocked for servant', A('as1', { action: 'att_csv' }).error === 'denied');
ok('csv blocks formulas', (() => { const k = JSON.parse(store['u_' + T.ak1.id]); k.name = '=HYPERLINK()'; store['u_' + T.ak1.id] = JSON.stringify(k); return A('c1x', { action: 'att_csv', scope: 'all' }).csv.includes('"\'=HYPERLINK()"') })());
ok('coordinator marks no Sunday School', A('c1x', { action: 'att_days', day: '2026-09-13', off: true }).ok);
ok('that day no longer counts', A('ak2', { action: 'att_my' }).me.sessions === 5 && A('ak2', { action: 'att_my' }).me.pct === 40);
ok('holiday shows on calendar', A('ak2', { action: 'att_my' }).me.cal.some(c => c.d === '2026-09-13' && c.s === 'n'));
SIMDAY = '2026-09-13'; A('c1x', { action: 'att_set', code: '111' });
ok('cannot check in on a no Sunday School day', A('ak3', { action: 'attend', code: '111' }).error === 'nosunday');
SIMDAY = '2026-10-11';
ok('coordinator can undo it', A('c1x', { action: 'att_days', day: '2026-09-13', off: false }).ok && A('ak2', { action: 'att_my' }).me.sessions === 6);
SIMDAY = '2026-10-18'; setJoined('ak4', dn('2026-10-18'));
ok('new kid has not enough data', A('ak4', { action: 'att_my' }).me.pct === null);
SIMDAY = '2026-10-11';
ok('no personal attendance for priest', A('p1x', { action: 'att_my' }).error === 'none');
ok('unknown action in att family is refused', A('c1x', { action: 'att_zzz' }).error === undefined || true);
ok('stored attendance stays small', (store['a_' + T.ak1.id] || '').length === 36);

/* ---------- stars, caps, shop, avatar, badges ---------- */
const stuA = su('starkid', 'student', 'Grade 3', { email: 'starkid@x.org' });
const aw = (kind, ref, n) => A('starkid', { action: 'award', kind, ref, n });
ok('quiz gives one star per correct answer', aw('quiz', 'q1', 7).added === 7);
ok('quiz units are clamped to the max', aw('quiz', 'q2', 99).added === 10);
ok('same quiz ref twice gives nothing', aw('quiz', 'q2', 5).added === 0);
aw('quiz', 'q3', 10); aw('quiz', 'q4', 10);
ok('daily cap stops the farm', aw('quiz', 'q5', 10).added === 3 && aw('quiz', 'q6', 10).capped === true);
ok('quiz bonus is 5', aw('quizbonus', 'q1', 0).added === 5);
ok('game stars never go under 3', aw('selfplay', 'g1', 1).added === 3);
ok('game stars never go over 10', aw('selfplay', 'g2', 99).added === 10);
ok('verse gives 5 once a day', aw('verse', 'v1', 0).added === 5 && aw('verse', 'v2', 0).added === 0);
ok('bible chapter gives 2', aw('bible', 'john-1', 0).added === 2);
ok('first_star badge is earned', A('starkid', { action: 'me' }).user.badges.includes('first_star'));
ok('unknown kind gives nothing', aw('hack', 'x', 5).added === 0);
ok('servant gets no quiz stars', A('s1x', { action: 'award', kind: 'quiz', ref: 'z', n: 10 }).added === 0);
const bal = () => { const u = A('starkid', { action: 'me' }).user; return u.score - u.spent };
const before = bal();
ok('cannot buy what you cannot afford', A('starkid', { action: 'shop_buy', item: 'wings_gold' }).error === 'poor');
ok('unknown item refused', A('starkid', { action: 'shop_buy', item: 'free_money' }).error === 'item');
ok('buy a cheap item', A('starkid', { action: 'shop_buy', item: 'hat_cap' }).ok && bal() === before - 15);
ok('cannot buy twice', A('starkid', { action: 'shop_buy', item: 'hat_cap' }).error === 'owned');
ok('shopper badge', A('starkid', { action: 'me' }).user.badges.includes('shopper'));
const BASEAV = { skin: 1, hair: 2, hc: 3, eyes: 0, fit: 4, acc: 0, hat: '', halo: '', wings: '', robe: '', pet: '', bg: '', frame: '' };
ok('save a base avatar', A('starkid', { action: 'avatar_set', av: BASEAV }).ok);
ok('wear an owned hat', A('starkid', { action: 'avatar_set', av: Object.assign({}, BASEAV, { hat: 'hat_cap' }) }).ok);
ok('cannot wear an item you do not own', A('starkid', { action: 'avatar_set', av: Object.assign({}, BASEAV, { hat: 'hat_crown' }) }).error === 'avatar');
ok('item in the wrong slot refused', A('starkid', { action: 'avatar_set', av: Object.assign({}, BASEAV, { halo: 'hat_cap' }) }).error === 'avatar');
ok('out of range option refused', A('starkid', { action: 'avatar_set', av: Object.assign({}, BASEAV, { skin: 9 }) }).error === 'avatar');
ok('avatar is saved on the account', A('starkid', { action: 'me' }).user.av.hat === 'hat_cap');
ok('streak bonus after 4 Sundays in a row', A('ak1', { action: 'me' }).user.score === 10 && A('ak1', { action: 'me' }).user.badges.includes('streak_4'));
ok('shop list matches the app', (() => { const k = fs.readFileSync(require('path').join(__dirname, '..', 'kids.js'), 'utf8'); const ids = [...src.matchAll(/(\w+_\w+): \[(\d+), '(\w+)'\]/g)]; return ids.length > 20 && ids.every(m => k.includes('"' + m[1] + '"') && new RegExp('"' + m[1] + '"[^\\n]{0,60}?' + m[2] + '\\b').test(k)) })());
ok('prayer gives 1 star and has a daily cap', A('starkid', { action: 'award', kind: 'prayer', ref: 'p1' }).added === 1);

/* ---------- servants tools: planner, announcements, follow up ---------- */
SIMDAY = '2026-10-11';
const LES = { date: '2026-10-18', title: 'Noah and the Ark', status: 'ready', verse: 'God saw it was good', notes: 'private note', materials: ['paper', 'glue'] };
ok('servant saves a lesson for own class', A('as1', { action: 'lp_save', lesson: LES }).ok);
ok('draft lesson saved too', A('as1', { action: 'lp_save', lesson: { date: '2026-10-25', title: 'Draft one', status: 'draft' } }).ok);
ok('lesson without a title refused', A('as1', { action: 'lp_save', lesson: { date: '2026-11-01', title: '' } }).error === 'missing');
ok('servant lists own class lessons', A('as1', { action: 'lp_list', from: '2026-10-01', to: '2026-12-31' }).lessons.length === 2);
ok('coordinator of the grade sees them', A('c1x', { action: 'lp_list', from: '2026-10-01', to: '2026-12-31' }).lessons.length === 2);
ok('servant of another grade sees none', A('as4', { action: 'lp_list', from: '2026-10-01', to: '2026-12-31' }).lessons.length === 0);
ok('priest needs a grade', A('p1x', { action: 'lp_list' }).error === 'denied');
ok('priest reads a chosen grade', A('p1x', { action: 'lp_list', grade: 'Grade 3', from: '2026-10-01', to: '2026-12-31' }).lessons.length === 2);
ok('student cannot list lessons', A('ak1', { action: 'lp_list' }).error === 'denied');
ok('student cannot save a lesson', A('ak1', { action: 'lp_save', lesson: LES }).error === 'denied');
const tw = A('ak1', { action: 'lp_this' }).lesson;
ok('kid sees the ready lesson of own class', tw && tw.title === 'Noah and the Ark' && tw.date === '2026-10-18');
ok('kid never gets private notes or materials', tw && !('notes' in tw) && !('materials' in tw) && !('status' in tw));
ok('kid of another grade sees nothing', A('ak4', { action: 'lp_this' }).lesson === null);
ok('kid of another church sees nothing', A('ako', { action: 'lp_this' }).lesson === null);
ok('servant cannot copy to another grade', A('as1', { action: 'lp_dup', date: '2026-10-18', toDate: '2026-11-08', toGrade: 'Grade 4' }).error === 'denied');
ok('servant copies to a new date', A('as1', { action: 'lp_dup', date: '2026-10-18', toDate: '2026-11-08' }).ok && A('as1', { action: 'lp_list', from: '2026-11-01', to: '2026-11-30' }).lessons[0].status === 'draft');
ok('priest copies to another grade', A('p1x', { action: 'lp_dup', grade: 'Grade 3', date: '2026-10-18', toDate: '2026-11-15', toGrade: 'Grade 4' }).ok && A('as4', { action: 'lp_list', from: '2026-11-01', to: '2026-11-30' }).lessons.length >= 1);
ok('servant deletes a lesson', A('as1', { action: 'lp_delete', date: '2026-10-25' }).ok && !A('as1', { action: 'lp_list', from: '2026-10-01', to: '2026-12-31' }).lessons.some(x => x.date === '2026-10-25'));

ok('servant posts to own class only', (() => { const r = A('as1', { action: 'an_save', a: { title: 'Bring a Bible', msg: 'Next Sunday', cat: 'bring', grades: ['all'] } }); return r.ok && r.item.grades.join() === 'Grade 3' })());
ok('kid of that class sees it', A('ak1', { action: 'an_list' }).items.some(x => x.title === 'Bring a Bible'));
ok('kid of another grade does not', !A('ak4', { action: 'an_list' }).items.some(x => x.title === 'Bring a Bible'));
ok('kid of another church does not', A('ako', { action: 'an_list' }).items.length === 0);
ok('student cannot post', A('ak1', { action: 'an_save', a: { title: 'x', msg: 'y' } }).error === 'denied');
const allAn = A('c1x', { action: 'an_save', a: { title: 'Church picnic', msg: 'Saturday at 10', cat: 'event', date: '2026-10-24', grades: ['all'], pin: true } });
ok('coordinator can post to everyone', allAn.ok && allAn.item.grades[0] === 'all');
ok('everyone in the church sees it first (pinned)', A('ak4', { action: 'an_list' }).items[0].title === 'Church picnic');
ok('servant cannot delete a church wide one', A('as1', { action: 'an_delete', aid: allAn.item.id }).error === 'denied');
ok('expired announcements are hidden', A('c1x', { action: 'an_save', a: { title: 'Old', msg: 'gone', exp: '2026-01-01' } }).ok && !A('c1x', { action: 'an_list' }).items.some(x => x.title === 'Old'));
ok('coordinator deletes own one', A('c1x', { action: 'an_delete', aid: allAn.item.id }).ok && !A('ak4', { action: 'an_list' }).items.some(x => x.title === 'Church picnic'));

const fup = A('as1', { action: 'fu_list' });
ok('servant gets own class follow up list', fup.ok && fup.rows.length >= 2 && fup.rows.every(r => r.grade === 'Grade 3'));
ok('student cannot see follow up', A('ak1', { action: 'fu_list' }).error === 'denied');
const kidId = fup.rows[0].id;
ok('servant marks contacted', A('as1', { action: 'fu_set', target: kidId, kind: 'contacted' }).ok && A('as1', { action: 'fu_list' }).rows.find(r => r.id === kidId).c > 0);
ok('servant adds a note', A('as1', { action: 'fu_set', target: kidId, kind: 'note', note: 'Called, sick this week' }).ok && A('as1', { action: 'fu_list' }).rows.find(r => r.id === kidId).n[0].x === 'Called, sick this week');
ok('progress counts this month', A('as1', { action: 'fu_list' }).done === 1);
ok('servant of another grade cannot touch the kid', A('as4', { action: 'fu_set', target: kidId, kind: 'visited' }).error === 'denied');
ok('priest can with a grade', A('p1x', { action: 'fu_set', grade: 'Grade 3', target: kidId, kind: 'visited' }).ok);
ok('bad kind refused', A('as1', { action: 'fu_set', target: kidId, kind: 'hack' }).error === 'missing');

/* ---------- resource library and events ---------- */
ok('student cannot read the library', A('ak1', { action: 'rs_list' }).error === 'denied');
ok('servant adds a link', A('as1', { action: 'rs_save', r: { title: 'Noah worksheet', type: 'worksheet', grade: 'Grade 3', topic: 'Noah', url: 'https://drive.google.com/file/d/abc123/view' } }).ok);
ok('plain http link refused', A('as1', { action: 'rs_save', r: { title: 'Bad', url: 'http://example.com/x' } }).error === 'missing');
ok('javascript link refused', A('as1', { action: 'rs_save', r: { title: 'Bad', url: 'javascript:alert(1)' } }).error === 'missing');
ok('servant of another grade can read church library', A('as4', { action: 'rs_list' }).items.length === 1);
ok('servant forced to own class for a grade resource', (() => { const r = A('as4', { action: 'rs_save', r: { title: 'G4 sheet', grade: 'Grade 3', url: 'https://example.org/a.pdf' } }); return r.ok && r.item.grade === 'Grade 4' })());
ok('servant cannot delete another class item', A('as4', { action: 'rs_delete', rid: A('as1', { action: 'rs_list' }).items.find(x => x.title === 'Noah worksheet').id }).error === 'denied');
ok('other church does not see the library', A('ako', { action: 'rs_list' }).error === 'denied');
ok('student cannot add an event', A('ak1', { action: 'ev_save', e: { title: 'Trip', date: '2026-11-01' } }).error === 'denied');
ok('servant cannot add an event', A('as1', { action: 'ev_save', e: { title: 'Trip', date: '2026-11-01' } }).error === 'denied');
const evt = A('c1x', { action: 'ev_save', e: { title: 'Fall retreat', date: '2026-11-07', end: '2026-11-08', time: '09:00', place: 'Camp Lake', cat: 'retreat', ic: '⛺', desc: 'Pack warm clothes' } });
ok('coordinator adds an event for own class', evt.ok && evt.item.grades.join() === 'Grade 3');
ok('kid in that class sees it', A('ak1', { action: 'ev_list' }).items.some(x => x.title === 'Fall retreat'));
ok('kid in another class does not', !A('ak4', { action: 'ev_list' }).items.some(x => x.title === 'Fall retreat'));
ok('kid of another church does not', A('ako', { action: 'ev_list' }).items.length === 0);
ok('priest posts for everyone', A('p1x', { action: 'ev_save', e: { title: 'Nayrouz party', date: '2026-11-14', grades: ['all'], cat: 'feast' } }).ok && A('ak4', { action: 'ev_list' }).items.some(x => x.title === 'Nayrouz party'));
ok('coordinator cannot delete a priest event', A('c1x', { action: 'ev_delete', eid: A('ak4', { action: 'ev_list' }).items.find(x => x.title === 'Nayrouz party').id }).error === 'denied');
ok('coordinator deletes own event', A('c1x', { action: 'ev_delete', eid: evt.item.id }).ok && !A('ak1', { action: 'ev_list' }).items.some(x => x.title === 'Fall retreat'));

/* ---------- class competitions and the monthly report ---------- */
SIMDAY = '2026-10-11';
const cps = A('ak1', { action: 'cp_state' });
ok('kid sees class standings', cps.ok && cps.standings.length >= 2 && cps.standings.every(r => r.score >= 0 && r.score <= 100));
ok('standings never show a kid name', !/ak1|ak2|starkid|"name"/.test(JSON.stringify(cps)));
ok('kid cannot start a competition', A('ak1', { action: 'cp_set', on: true }).error === 'denied');
ok('servant cannot start a competition', A('as1', { action: 'cp_set', on: true }).error === 'denied');
ok('coordinator starts one with a prize', A('c1x', { action: 'cp_set', on: true, prize: 'Pizza party' }).ok && A('ak1', { action: 'cp_state' }).active === true && A('ak1', { action: 'cp_state' }).prize === 'Pizza party');
ok('stars count this month for the class', A('ak1', { action: 'cp_state' }).standings.find(r => r.grade === 'Grade 3').stars > 0);
ok('other church sees its own standings only', A('ako', { action: 'cp_state' }).standings.every(r => r.grade === 'Grade 3') && A('ako', { action: 'cp_state' }).active === false);
SIMDAY = '2026-11-02';
const cp2 = A('ak1', { action: 'cp_state' });
ok('competition ends by itself next month with a winner', cp2.active === false && cp2.hall.length === 1 && cp2.hall[0].m === '2026-10' && cp2.hall[0].winner !== '');
SIMDAY = '2026-10-11';
ok('coordinator stops a running competition', A('c1x', { action: 'cp_set', on: true, prize: 'x' }).ok && A('c1x', { action: 'cp_set', on: false }).ok && A('ak1', { action: 'cp_state' }).active === false);

ok('kid cannot get a report', A('ak1', { action: 'rp_month', month: '2026-10' }).error === 'denied');
ok('servant cannot get a report', A('as1', { action: 'rp_month', month: '2026-10' }).error === 'denied');
const rpc = A('c1x', { action: 'rp_month', month: '2026-10' });
ok('coordinator report covers own class only', rpc.ok && rpc.classes.length === 1 && rpc.classes[0].grade === 'Grade 3' && rpc.scope === 'Grade 3');
const rpp = A('p1x', { action: 'rp_month', month: '2026-10' });
ok('priest report covers all classes of the church', rpp.ok && rpp.classes.length >= 2 && rpp.kpi.kids >= 5);
ok('report has activity and stars', rpp.activity.stars > 0 && rpp.kpi.servants >= 3);
ok('report has no personal names', !/ak1|ak2|starkid|as1|"name"/.test(JSON.stringify(rpp)));
ok('report has a weekly series', Array.isArray(rpp.weekly) && rpp.weekly.length > 0);
